# Select image from https://hub.docker.com/_/php/
image: marciodojr/phpstart-apache-docker-image:dev
 
# Select what we should cache
cache:
  paths:
  - vendor/
 
before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq
- composer install
 
services:
- mysql
 
variables:
    - MYSQL_DATABASE: servermail
    - MYSQL_USER: servermailadmin
    - MYSQL_PASSWORD: admin
    - MYSQL_ROOT_PASSWORD: root
    - DEV_MODE: 1
    - DB_HOST: mysql
    - DB_PORT: 3306
    - DB_NAME: servermail
    - DB_USER: servermailadmin
    - DB_PASS: admin
    - APP_SECRET: holly_molly!
 
test:mysql:
  script:
  - vendor/bin/phpunit --coverage-text --testdox
  - allow_failure: true