version: '3'
services:
    app:
        env_file: .docker/.env
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: phpstart-docker
        ports:
            - 3000:80
        volumes:
            - .:/srv/vhosts/phpApp
        links:
            - mysql
            - redis
            - beanstalk
    mysql:
        env_file: .docker/.env
        image: mysql:5.7
        ports:
            - 13306:3306
    redis:
        image: redis:4.0-alpine
        ports:
            - 16379:6379
    beanstalk:
        image: schickling/beanstalkd
        ports:
            - 21300:11300
    composer:
        restart: 'no'
        image: composer:1.6.5
        volumes:
            - .:/srv/vhosts/phpApp
        working_dir: /srv/vhosts/phpApp
        command: install --ignore-platform-reqs
    node:
        restart: 'no'
        image: node:8
        volumes:
            - .:/srv/vhosts/phpApp
        working_dir: /srv/vhosts/phpApp
        command: /bin/bash -c "npm install grunt-cli -g && npm install"

