version: '3'
services:
    app:
        env_file: .docker/.env
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: phpstart-docker
        ports:
            - 4000:80
        # volumes:
            # - .:/srv/vhosts/phpApp
        links:
            - mysql
    mysql:
        env_file: .docker/.env
        image: mysql:5.7
        ports:
            - 13306:3306
