version: '3.1'
services:
    mysql:
        image: marciodojr/emailprovider-db:latest-dev
        container_name: emailprovider-mysql
        environment:
            - MYSQL_DATABASE=servermail
            - MYSQL_USER=servermailadmin
            - MYSQL_PASSWORD=admin
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/mysql/mysql-data:/var/lib/mysql
        working_dir: /srv/vhosts/phpApp
        ports:
            - 13306:3306

    composer:
        image: composer:1.6.5
        container_name: emailprovider-composer
        volumes:
            - .:/srv/vhosts/phpApp
        working_dir: /srv/vhosts/phpApp
        command: install --ignore-platform-reqs

    node:
        image: node:10.6.0-alpine
        container_name: emailprovider-node
        environment:
            - SERVERNAME=webserver
        volumes:
            - .:/srv/vhosts/phpApp
        working_dir: /srv/vhosts/phpApp
        command: /bin/sh -c "npm install grunt-cli && npm install && npm run dev"
        ports:
            - 3000:3000
            - 3001:3001
        depends_on:
            - composer
            - webserver

    php-fpm:
        image: marciodojr/phpstart:1.2.0
        container_name: emailprovider
        environment:
            - DB_HOST=mysql
            - DB_NAME=servermail
            - DB_USER=servermailadmin
            - DB_PASS=admin
            - APP_SECRET=holly_molly!
            - APP_COOKIE_NAME=auth_token
        working_dir: /srv/vhosts/phpApp
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
            - ./cache:/srv/vhosts/phpApp/cache
        depends_on:
            - mysql

    webserver:
        image: nginx:1.14.0-alpine
        container_name: emailprovider-webserver
        working_dir: /srv/vhosts/phpApp
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 2999:80
        depends_on:
            - php-fpm
