version: '3.1'
services:
    mysql:
        image: marciodojr/emailprovider-db:latest-dev
        container_name: emailprovider-mysql
        environment:
            - MYSQL_DATABASE=servermail
            - MYSQL_USER=servermailadmin
            - MYSQL_PASSWORD=admin
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/mysql/mysql-data:/var/lib/mysql
        working_dir: /srv/vhosts/phpApp
        ports:
            - 13306:3306

    php-apache:
        image: marciodojr/phpstart-apache-docker-image:1.0.0
        container_name: emailprovider
        environment:
            - DEV_MODE=1
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_NAME=servermail
            - DB_USER=servermailadmin
            - DB_PASS=admin
            - APP_SECRET=holly_molly!
        working_dir: /srv/vhosts/phpApp
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/php/php-ini-overrides.ini:/etc/php/7.2/apache2/conf.d/99-overrides.ini
            - ./cache:/srv/vhosts/phpApp/cache
            - ./.docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - 3000:80
        depends_on:
            - mysql
